name: Playwright Tests

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: '30 7 * * *'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HEADLESS: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          playwright install --with-deps

      - name: Clean old allure results
        run: rm -rf allure-results

      - name: Run Tests
        run: |
          pytest --alluredir=allure-results \
                 --cov=. \
                 --cov-report=xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Get Allure History
        if: always()
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-history
          keep_files: true